import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowRight, Instagram, Menu, X, Search, SlidersHorizontal } from 'lucide-react';
import artworks from './data/artworks.json';
import './styles.css';
const instagram='https://www.instagram.com/theweekendartist__/';
const art=(id)=>artworks.find(a=>a.id===id);
function App(){
 const [menu,setMenu]=useState(false),[category,setCategory]=useState('All works'),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[limit,setLimit]=useState(8),[selected,setSelected]=useState(null);
 const dialog=useRef(null),lastFocus=useRef(null);
 const ordered=[20,1,25,14,11,21,34,6,...artworks.map(a=>a.id).filter(id=>![20,1,25,14,11,21,34,6].includes(id))].map(art);
 const filtered=ordered.filter(a=>(category==='All works'||a.category===category)&&(status==='all'||a.status===status)&&a.title.toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[limit,category,status,search]);
 useEffect(()=>{if(selected){lastFocus.current=document.activeElement;dialog.current.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[selected]);
 const reset=(fn,value)=>{fn(value);setLimit(8)};
 return <>
 <header className="header"><a className="wordmark" href="#home" aria-label="Himanshi Kadu home">himanshi<span>.</span><small>THE WEEKEND ARTIST</small></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation">{[['The gallery','gallery'],['Meet the artist','about'],['Behind the canvas','studio']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="nav-contact" href="#contact">Let’s connect <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main><section id="home" className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> A LITTLE COLOUR. A LOT OF SOUL.</div><h1>Ordinary moments.<br/><span>Extraordinary</span><br/><em>on canvas.</em><span className="hero-spark">✳</span></h1><p>For the places we dream of. The feelings we can’t put<br className="desktop-br"/> into words. And the walls that deserve a little magic.</p><div className="hero-actions"><a className="button dark" href="#gallery">Find your piece <ArrowUpRight size={19}/></a><a className="text-link" href="#about">Meet Himanshi <span>↗</span></a></div><div className="hero-note"><span className="note-line"/> ORIGINAL ART. MADE WITH HEART.</div></div>
 <div className="hero-art"><div className="sun-circle"/><span className="orbit orbit-one"/><span className="orbit orbit-two"/><span className="handwritten hero-handwriting">a world of my own <span>⤵</span></span><button className="floating-painting painting-left" onClick={()=>setSelected(art(20))} aria-label="View When the Meadow Dreams"><img src={art(20).image} alt="Purple twilight over a painted meadow of daisies"/><span>little moments, forever.</span></button><div className="portrait-wrap"><img className="hero-portrait" src="/portrait.webp" alt="Himanshi Kadu, The Weekend Artist" fetchPriority="high"/></div><button className="floating-painting painting-right" onClick={()=>setSelected(art(11))} aria-label="View Fields of Daydreams"><img src={art(11).image} alt="A sunlit wildflower meadow painting"/></button><div className="artist-label"><span className="label-star">✳</span><div>Himanshi Kadu<small>ARTIST. DREAMER. COLOUR LOVER.</small></div></div><div className="round-seal">HANDPAINTED<br/><span>♡</span><br/>WITH LOVE</div></div>
 <a href="#gallery" className="scroll-note"><ArrowDown size={15}/> SCROLL TO WANDER</a><span className="hero-side-note">A SMALL WINDOW INTO MY WORLD — EST. WITH LOVE</span></section>
 <div className="marquee" aria-label="Original paintings, made with love"><div>{Array.from({length:4},(_,i)=><span key={i}>A little wonder for your walls <i>✳</i> One of a kind. Just like you. <i>✳</i></span>)}</div></div>
 <section id="gallery" className="gallery section-pad"><div className="section-heading reveal"><div><div className="eyebrow">01 / THE COLLECTION</div><h2>Find something<br/>that <em>feels like you.</em></h2></div><div className="heading-aside"><p>A collection of places, feelings, and little obsessions.<br/>Each one painted slowly. Each one a story of its own.</p><span>{artworks.length} ORIGINAL WORKS, ENDLESS LITTLE STORIES <ArrowDown size={14}/></span></div></div>
 <div className="gallery-controls"><div className="tabs" aria-label="Filter artwork category">{['All works','Nature','Dreamscapes','Devotion','Wildlife'].map(c=><button className={category===c?'active':''} key={c} onClick={()=>reset(setCategory,c)} aria-pressed={category===c}>{c}{c==='All works'&&<sup>{artworks.length}</sup>}</button>)}</div><div className="availability"><SlidersHorizontal size={15}/><select aria-label="Filter availability" value={status} onChange={e=>reset(setStatus,e.target.value)}><option value="all">All availability</option><option value="available">Available works</option><option value="sold">Sold works</option></select></div></div>
 <div className="results-bar"><span>{filtered.length} {filtered.length===1?'artwork':'artworks'} to fall in love with</span><label className="search"><Search size={15}/><input value={search} onChange={e=>reset(setSearch,e.target.value)} placeholder="Find a little wonder…" aria-label="Search artworks"/>{search&&<button onClick={()=>setSearch('')} aria-label="Clear search"><X size={14}/></button>}</label></div>
 <div className="art-grid">{filtered.slice(0,limit).map((a,i)=><button key={a.id} className="art-card reveal" onClick={()=>setSelected(a)} style={{'--delay':`${i%4*65}ms`}}><div className="art-image"><img src={a.image} alt={a.title} loading="lazy"/><span className={'status '+a.status}><i/>{a.status==='sold'?'Sold · Found a home':'Available'}</span><span className="view-art">Take a closer look <ArrowUpRight size={17}/></span></div><div className="art-info"><div><h3>{a.title}</h3><span>{a.category} · Original painting</span></div><ArrowUpRight size={21}/></div></button>)}</div>
 {filtered.length===0&&<div className="empty"><h3>No paintings found this time.</h3><p>Try another title or explore the full collection.</p><button className="button outline" onClick={()=>{setSearch('');setStatus('all');setCategory('All works')}}>Explore all works <ArrowRight size={16}/></button></div>}
 {limit<filtered.length&&<div className="load-more"><button className="button outline" onClick={()=>setLimit(limit+8)}>A little more to explore <ArrowDown size={17}/></button><span>Showing {Math.min(limit,filtered.length)} of {filtered.length} works</span></div>}
 </section>
 <section id="about" className="about section-pad"><div className="about-image reveal"><img src="/profile.webp" alt="Himanshi smiling in a sunlit garden" loading="lazy"/><span className="photo-caption handwritten">The hands behind the colours. ♡</span><span className="about-stamp">MADE SLOWLY<br/><span>✳</span><br/>FELT DEEPLY</span></div><div className="about-copy reveal"><div className="eyebrow">02 / THE HEART BEHIND THE ART</div><h2>Hi, I’m Himanshi.<br/><em>A little paint.<br/>A little daydream.</em></h2><p>Welcome to my little corner of colour. I’m the artist behind <strong>The Weekend Artist</strong> — a space for turning everyday inspiration into something you can hold on to.</p><p>From quiet landscapes to soulful portraits, my canvas is where curiosity takes the lead. A sky that stopped me in my tracks. A beloved little face. A feeling that stayed.</p><p className="about-quote">“Some things are better said in colour.”</p><a className="text-link" href={instagram} target="_blank" rel="noreferrer">Step into my world <Instagram size={18}/></a></div></section>
 <section id="studio" className="studio section-pad"><div className="section-heading reveal"><div><div className="eyebrow">03 / A PEEK BEHIND THE CANVAS</div><h2>A little messy.<br/><em>A whole lot of magic.</em></h2></div><div className="heading-aside"><p>The process, the paint-covered days, the final reveal.<br/>Follow along for the stories behind the strokes.</p><a className="text-link" href={instagram} target="_blank" rel="noreferrer"><Instagram size={18}/> @theweekendartist__ <ArrowUpRight size={17}/></a></div></div><div className="studio-grid">{[9,23,16,27].map((id,i)=><a className="studio-tile reveal" href={instagram} key={id} target="_blank" rel="noreferrer"><img src={art(id).image} alt={['Painting a colourful landscape at sunset','A waterfall artwork out in nature','Art on a sacred journey','An ocean painting beside the water'][i]} loading="lazy"/><span><Instagram size={20}/><ArrowUpRight size={20}/></span></a>)}</div><p className="studio-caption">A little art. A little life. Everything in between. <span>See you on Instagram ↗</span></p></section>
 <section id="contact" className="contact section-pad"><div className="contact-top"><span className="eyebrow">GOOD ART STARTS A CONVERSATION.</span><span>LET’S MAKE IT PERSONAL ↘</span></div><div className="contact-main reveal"><h2>Your wall.<br/><em>Our next story.</em></h2><div><p>Found a piece you love?<br/>Have something special in mind?<br/>I’d love to hear from you.</p><a className="button cream" href={instagram} target="_blank" rel="noreferrer">Say hello on Instagram <ArrowUpRight size={19}/></a></div><span className="contact-flower">✳</span></div><footer><a className="footer-logo" href="#home">himanshi.</a><span>© {new Date().getFullYear()} Himanshi Kadu · Made with a little love.</span><a href="#home">BACK TO TOP <ArrowUpRight size={15}/></a></footer></section>
 </main>
 <dialog ref={dialog} className="art-dialog" aria-labelledby="artwork-title" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}>{selected&&<div className="dialog-inner"><button className="close-dialog" aria-label="Close artwork details" onClick={()=>setSelected(null)}><X size={22}/></button><div className="dialog-image"><img src={selected.image} alt={selected.title}/></div><div className="dialog-copy"><div className="eyebrow">AN ORIGINAL BY HIMANSHI KADU</div><span className={'status '+selected.status}><i/>{selected.status==='sold'?'Sold · Found a home':'Available to collect'}</span><h2 id="artwork-title">{selected.title}</h2><p>{selected.description}</p><dl><div><dt>Collection</dt><dd>{selected.category}</dd></div><div><dt>Details & pricing</dt><dd>Ask the artist</dd></div></dl><p className="inquiry-note">{selected.status==='sold'?'This piece has found its home. Love this style? Ask Himanshi about a similar commission.':'Make this little world a part of yours. Message Himanshi for the price, dimensions, and delivery details.'}</p><a className="button dark" href={instagram} target="_blank" rel="noreferrer">{selected.status==='sold'?'Ask about a similar piece':'Enquire about this painting'}<ArrowUpRight size={18}/></a><small>Mention “{selected.title}” in your message.</small></div></div>}</dialog>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
